const videoData = {
    0:{
        name:'sorrr.mp4',
        location:'./assets/sorrr.mp4'
    },
    1:{
        name:'aa1.mp4',
        location:'./assets/aa1.mp4'
    },
    2:{
        name:'aa4.mp4',
        location:'./assets/aa4.mp4'
    },
    3:{
        name:'aa5.mp4',
        location:'./assets/aa5.mp4'
    },
    4:{
        name:'aa6.mp4',
        location:'./assets/aa6.mp4'
    },
    5:{
        name:'aa7.mp4',
        location:'./assets/aa7.mp4'
    },
    6:{
        name:'aa8.mp4',
        location:'./assets/aa8.mp4'
    },
    7:{
        name:'aa9.mp4',
        location:'./assets/aa9.mp4'
    },
    8:{
        name:'aa10.mp4',
        location:'./assets/aa10.mp4'
    },
    9:{
        name:'aa11.mp4',
        location:'./assets/aa11.mp4'
    },
    10:{
        name:'aa12.mp4',
        location:'./assets/aa12.mp4'
    }
}

module.exports = videoData